language: python
python:
    - "3.6"
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_extended_0.76.5_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
script:
    - hugo --minify
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: source
    local_dir: public
    repo: tongweijiayou/tongweijiayou.com
    fqdn: tongweijiayou.com
    target_branch: master
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
